version: 2.1
jobs:
  build-and-test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Package
          command: |
            yarn install
      - run:
          name: build
          command: |
            yarn build
      - run:
          name: test
          command: |
            yarn test
workflows:
  main:
    jobs:
      - build-and-test
